# Generated by Django 3.2.8 on 2021-10-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('number', models.FloatField(verbose_name='Number')),
                ('text', models.TextField(max_length=500, verbose_name='Text')),
                ('list', models.TextField(max_length=500, verbose_name='List')),
            ],
        ),
    ]
